services:
  ai_chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_chat
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ai_chat_network
    command: >
      sh -c "python src/store_data.py && streamlit run src/main.py --server.address=0.0.0.0"
  
  postgres:
    image: ankane/pgvector
    container_name: postgres_pgvector
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - ai_chat_network

volumes:
  postgres_data:
  

networks:
  ai_chat_network:
    driver: bridge